### ISSUE TITLE
pypi tarball misses tests

### ISSUE THREAD

**Issue by mgorny** [pwaller/pyprof2calltree#17]
The tarball uploaded to pypi (for version 1.4.0) does not have the 'tests' directory. I think it should be added to MANIFEST.in.

**Comment by pwaller** [comment]
I'm not familiar with a need to distribute the tests - if you want to run the tests you can just clone the repository, no? Out of interest, are there significant consequences to not distributing the tests?

That said, if you send a pull request I'll happily include it. Is it just a matter of adding `include tests`, or something else?

**Comment by pwaller** [comment]
Fixed, live on pypi now.
