### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by pwaller** [pwaller/pyprof2calltree#48]
Hi @jdufresne,

I'm making this issue to remind me to make a new release. Let me know if you would like me to do it sooner rather than later. I'll hold off for a moment in case you have any more fixes in the near term.

**Comment by jdufresne** [comment]
A new release sounds good to me. Thanks for maintaining the project!

**Comment by pwaller** [comment]
v1.4.4 is released:

- https://github.com/pwaller/pyprof2calltree/releases/tag/v1.4.4
- https://pypi.org/project/pyprof2calltree/1.4.4/
