### ISSUE TITLE
Information: can not find files for the specified model (s)

### ISSUE THREAD

**Issue by AmjadHD** [pwaller/pyprof2calltree#49]
```cmd
Microsoft Windows [version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Tous droits réservés.

C:\Users\User\Desktop\Tfach\xdf>python -m cProfile -o out.cprof profile_code.py

C:\Users\User\Desktop\Tfach\xdf>pyprof2calltree -i out.cprof -k
launching kcachegrind
Information : impossible de trouver des fichiers pour le(s) modèle(s) spécifié(s
).

C:\Users\User\Desktop\Tfach\xdf>
```
I'm using profile_code.py as a test file
it says it can not find files for the specified model (s). why is that ?

OS: Windows 7
pyprof2calltree: 1.4.4
python: 3.7

**Comment by pwaller** [comment]
I think the error message is coming from kcachegrind - I don't have any further insight on this error message.

If you can find some evidence that this is a bug in pyprof2calltree, or provide a reproducer, please report back and I will reopen.
