### ISSUE TITLE
medium term plan: will pyprof2calltree be merged into qcachegrind/kcachegrind or kdedevelop-python?

### ISSUE THREAD

**Issue by sten0** [pwaller/pyprof2calltree#50]
Hi,

I'm investigating packaging pyprof2calltree for Debian, but I'm wondering if the plan is for it to remain an independent project, or if it might be merged into qcachegrind/kcachegrind or kdevelop-python (medium term).  If the plan is to merge it then I'll wait for the merge, otherwise I'll go ahead and package it.

Looking forward to your reply,
Cheers!
Nicholas

**Comment by pwaller** [comment]
Hi @sten0, sorry for the delay in response. Things have been busy.

I don't have contact with any other developers who might want to merge. As far as I'm concerned this is a standalone project which facilitates this functionality.

Of course I'd be happy to see functionality added to kcachegrind or other packages, but in the meantime I would be happy to see pyprof2calltree packaged for Debian and other distributions.

If there is someone who wants to try and aggregate effort into one place I'd certainly entertain the idea.

Let me know if I can facilitate any of these things in any way, and I'll try to be a bit more responsive.

**Comment by sten0** [comment]
Hi @pwaller, thank you for the confirmation.  Pyprof2calltree is now in Debian, and it also migrated in time for the Ubuntu 20.04 release.  Usually we follow up with a PR for README.md to add installation instructions for Debian and derivative systems.  Shall I go ahead and file one?  I noticed the project doesn't seem to have any installation instructions, which is why I'm not sure.

**Comment by pwaller** [comment]
> Shall I go ahead and file one?

Sounds great, thanks! :)
