### ISSUE TITLE
Support for different scales

### ISSUE THREAD

**Issue by meesha7** [pwaller/pyprof2calltree#57]
Hi! I was wondering if there's any plan to implement different scales other than nanoseconds? While these are great for profiling any fast enough code, I often find myself in a situation where I profile long running scripts or Django requests that won't be faster than order of milliseconds. Having nanoseconds in the output file is then redundant and difficult to read as I am only interested in the range of roughly 1ms - 1s. In the past I hacked my local pyprof2calltree installation to support both ms and ns. So I would like to ask if anyone else has run into a similar need and if it would be worth to implement this? (I'd be happy to do so).

**Comment by pwaller** [comment]
Patches which are backwards compatible are welcome!

**Comment by staticf0x** [comment]
The referenced PR is merged now, I'm closing this.
